model_config:
  model_name: "qwen2.5-0.5b-instruct"
  model_id: "Qwen/Qwen2.5-0.5B-Instruct"
  model_source: "huggingface"
  model_display: false
  intermediate_ckpt_dir: "/tmp/intermediate_ckpt/nl2sql_qwen2p5_0p5b"
  model_download_path: "/tmp/models"
  mesh:
    shape: "(1,1)"
    axis_names: "('fsdp','tp')"
  rng_seed: 42
actor_model_config:
  lora_config: null
  model_display: false
  mesh:
    shape: "(1,1)"
    axis_names: "('fsdp','tp')"
reference_model_config:
  model_name: "qwen2.5-0.5b-instruct"
  model_id: "Qwen/Qwen2.5-0.5B-Instruct"
  model_source: "huggingface"
  model_display: false
  intermediate_ckpt_dir: "/tmp/intermediate_ckpt/nl2sql_qwen2p5_0p5b"
  model_download_path: "/tmp/models"
  mesh:
    shape: "(1,1)"
    axis_names: "('fsdp','tp')"
  rng_seed: 42
rollout_model_config:
  model_name: "qwen2.5-0.5b-instruct"
  model_id: "Qwen/Qwen2.5-0.5B-Instruct"
  model_source: "huggingface"
  model_display: false
  intermediate_ckpt_dir: "/tmp/intermediate_ckpt/nl2sql_qwen2p5_0p5b"
  model_download_path: "/tmp/models"
  mesh:
    shape: "(1,1)"
    axis_names: "('fsdp','tp')"
tokenizer_config:
  tokenizer_type: "huggingface"
  tokenizer_path: "Qwen/Qwen2.5-0.5B-Instruct"
  add_bos: False
  add_eos: True
data_module: "examples/rl/grpo/nl2sql/data.py:create_dataset"
dataset_name: "nl2sql"
batch_size: 1
num_batches: 10
num_test_batches: 2
num_train_epochs: 1
rl_training_config:
  actor_optimizer_config:
    opt_type: "adamw"
    peak_value: 3e-6
    schedule_type: "warmup_cosine_decay_schedule"
    init_value: 0.0
    end_value: 0.0
    warmup_ratio: 0.1
    warmup_steps: 1
    decay_steps: 10
    b1: 0.9
    b2: 0.99
    weight_decay: 0.1
    max_grad_norm: 0.1
  eval_every_n_steps: 2
  max_steps: 10
  metrics_logging_options:
    log_dir: "/tmp/tensorboard/grpo_nl2sql_qwen2p5_0p5b"
    flush_every_n_steps: 20
  checkpointing_options:
    save_interval_steps: 10
    max_to_keep: 2
  profiler_options: {}
rollout_config:
  total_generation_steps: 256
  max_prompt_length: 256
  temperature: 0.2
  top_p: 0.95
  top_k: 50
rollout_engine: "vanilla"
offload_to_cpu: False
verl_compatible: false
grpo_config:
  num_generations: 2
  num_iterations: 1
  beta: 0.08
  epsilon: 0.2
reward_functions:
  - "tunix/cli/reward_fn/nl2sql.py"

